language: go
go:
  - "1.12"

# safelist
branches: 
  only:
    - master

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script: 
  - make build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
  - make docker-publish