apiVersion: kyverno.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: check-resources
spec:
  validationFailureAction: "audit"
  rules:
  - name: check-pod-resources
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "CPU and memory resource requests and limits are required"
      pattern:
        spec:
          containers:
          - name: "*"
            resources:
              requests:
                memory: "?*"
                cpu: "?*"
              limits:
                memory: "?*"
                cpu: "?*"
