apiVersion: kyverno.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: validate-probes
spec:
  rules:
  - name: check-probes
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Liveness and readiness probes are required"
      pattern:
        spec:
          containers:
          - livenessProbe:
              periodSeconds: ">0"      
            readinessProbe:
              periodSeconds: ">0"

